spring.application.name=fetchkar-backend

spring.datasource.url=jdbc:h2:mem:fetchkar;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.defer-datasource-initialization=true

# H2 Console (optional, good for debugging)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

jwt.secret=94a08da1fecbb6e8b46990538c7b50b2a8d3e2307b22a08ab9e5c46e30b65401
jwt.expiration=86400000

server.port=8081
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
